### ISSUE TITLE
Getting error related to GeckoDriver

### ISSUE THREAD

**Issue by olhartley** [Quoorex/minecraft-server-eu-bot#2] opened 2020-04-15 11:37 UTC
selenium.common.exceptions.WebDriverException: Message: Expected absolute path: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://marionette/content/addon.js :: install :: line 70"  data: no]

**Comment by Quoorex** [comment] 2020-04-16 10:56
Could be fixed with the new commits. You should try updating your repository and running the program again. But please note that the installation process has slightly changed and you must now use Poetry instead of Pipenv. Just take a look at the README for the updated installation guide.

**Comment by olhartley** [comment] 2020-04-16 11:05
Still getting the same error :/ Its something to do with PATH 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)

**Comment by Dibsymodzz** [comment] 2020-04-20 00:47
It seems like I have the same Problem and i am really lost in this kind of topic. Ive tryed to fix it but it didnt work. I have replaced the Geckodriver with an older one because it said that it dosnt have enough permission. I would appreciate help! 
https://prnt.sc/s2jnx9

**Comment by olhartley** [comment] 2020-04-20 00:51
I’ve tried to create my own version, it works slightly but it can’t find the element name

**Comment by Dibsymodzz** [comment] 2020-04-20 02:01
@emmyghast You make you own bot ?

**Comment by Dibsymodzz** [comment] 2020-04-20 16:07
and how can I fix that now?

**Comment by Quoorex** [comment] 2020-04-21 17:25
I will try to look into this again later on. I have only tested the software on Linux so far and I will try running this on Windows. There are many things about this project that I have to rework anyway. @emmyghast Could you tell me what kind of things you've changed?

**Comment by olhartley** [comment] 2020-04-21 17:56
I meant I have attempted to make my own but it’s very simple and just goes to the site, finds the element id or name and clicks enter, no captcha or proxy as I can just get on a vpn

**Comment by Quoorex** [comment] 2020-04-22 11:14
With the newest commit the program should now also function on Windows.

**Comment by Dibsymodzz** [comment] 2020-04-22 14:16
https://prnt.sc/s40yer HELP :D

**Comment by olhartley** [comment] 2020-04-22 14:26
So the error you are getting basically means that it cant find the captcha, since each different website calls the id something different, im still looking for the right id, the way to look for it is by going to the voting page and pressing f12 or ctrl + shift i or right click and click inspect element. 
Once you open the inspect element tab, click on inspector and find the captcha part, in main.py the captcha locater is line 129, you can change the type of part it looks for with, driver.find_element_by_class_name or driver.find_element_by_name, im still looking for the right one

**Comment by Quoorex** [comment] 2020-04-22 16:37
I know that this error also sometimes appears and I will try to fix it. To  briefly explain this: 
The program installs the Firefox Extension [Buster](https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver) which is used the solve the captchas. Buster listens to the audio version of the Recaptcha and uses a public Text-to-Speech API to translate that audio into text. That text is then entered and the captcha thereby solved. The problem is that this API has a limit as to how often it can be used per minute. All Buster Users together count towards that limit because they all use the same API key provided by the developer of Buster. That means if too many users use Buster at the same time, it fails to solve the captcha. 
The bot currently does not handle this correctly and produces said error (or so I think). What can be done is to either let the bot retry solving the captcha with Buster until it works, or to implement a captcha solving service into the program, which would make it run way faster (that has been on the TODO list for too long now).

**Comment by Quoorex** [comment] 2020-04-23 16:45
I've opened a new issue for that error (#3) and will be closing this one.

**Closed as completed by Quoorex** 2020-04-23 16:45 UTC
